version: "3.9"
services:
  postgres:
    container_name: spring-boot-app-template-postgres
    networks:
      - proxynet
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "spring-boot-app-template"
    ports:
      - "5432:5432"
    expose:
      - "5432"

networks:
  proxynet:
    name: spring-boot-app-template-network
