version: "3.9"
services:
  spring-boot-app-template:
    container_name: spring-boot-app-template
    build:
      context: .
      dockerfile: ./spring-boot-app-template/Dockerfile
    networks:
      - proxynet
    environment:
      SERVICE_PORT: 8080
    ports:
      - "8080:8080"

networks:
  proxynet:
    name: spring-boot-app-template-network
