name: build

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  pull_request_target:
    types: [ opened, synchronize, reopened, ready_for_review ]


jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        service: [ spring-boot-app-template ]
    uses: yonatankarp/github-actions/.github/workflows/build.yml@v1
    with:
      app_name: ${{ matrix.service }}

  dependabot_auto_merge:
    needs: ci
    if: ${{ github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]' }}
    uses: yonatankarp/github-actions/.github/workflows/dependabot-auto-merge.yml@v1
